```{r}
# Title: Combine WQ Data
# Purpose: combine different wq data sets for drought synthesis
# Author: Sarah Perry
# Contact: sarah.perry@water.ca.gov
```

```{r}
library(tidyverse)
library(deltamapr)
library(lubridate)
library(sf)
library(sp)
source('Water_Quality/wq_funcs.R')
```

```{r, message=FALSE}
# import data
fp_abs_emp <- 'WQ_Team/processed_data/EMPWQData1975-2020.csv'
fp_abs_sf <- 'WQ_Team/processed_data/SFBayWQData1969-2021.csv'
fp_abs_wsc <- 'WQ_Team/processed_data/USGS_CAWSC_1971-2021.csv'

df_emp <- read_csv(drought_abs_path(fp_abs_emp))
df_sf <- read_csv(drought_abs_path(fp_abs_sf))
df_wsc <- read_csv(drought_abs_path(fp_abs_wsc))
```

```{r}
# clean up data
df_sf$Station <- as.character(df_sf$Station)
df_emp$DON <- as.numeric(df_emp$DON)
df_emp$DissAmmonia <- as.numeric(df_emp$DissAmmonia)
df_emp$DissOrthophos <- as.numeric(df_emp$DissOrthophos)
df_sf$DS <- 'SF'
df_emp$DS <- 'EMP'
df_wsc$DS <- 'WSC'

# subset dfs
df_sf <- subset(df_sf, select = c('Date', 'Month', 'Year', 'Region', 'Station', 'Season', 'WY', 'Long_term', 'Latitude', 'Longitude', 'DissAmmonia', 'DissNitrateNitrite', 'DissOrthophos', 'DissSilica', 'DS'))
df_emp <- subset(df_emp, select = c('Date', 'Month', 'Year', 'Region', 'Station', 'Season', 'WY', 'Long_term', 'Latitude', 'Longitude', 'DissAmmonia', 'DissNitrateNitrite', 'DissOrthophos', 'DissSilica', 'DS'))
# df_wsc <- subset(df_wsc, select = c('Date', 'Month', 'Year', 'Region', 'Station', 'Season', 'WY', 'Long_term', 'Latitude', 'Longitude', 'DissAmmonia', 'DissNitrateNitrite', 'DissOrthophos', 'DS'))
```

```{r}
# combine and format
df_wq <- bind_rows(df_sf, df_emp)
df_wq$Date <- format(as.Date(df_wq$Date, format = '%Y-%m-%d'), '%Y-%m')
row.names(df_wq) <- NULL

df_wq <- subset(df_wq, Date > '1975-01')

df_wq <- df_wq %>%
  group_by(Station, Region, Date, Season, WY, Long_term, DS) %>%
  summarise(across(DissAmmonia:DissSilica, ~mean(., na.rm = TRUE)), .groups = 'drop')

# write file
write_csv(df_wq, drought_abs_path('WQ_Team/processed_data/combined_wq_data.csv'))
```


```{r}
# checks
# df_wq_sub <- subset(df_wq, SubRegion == 'Lower Sacramento River')
df_wq_sub <- subset(df_wq, DS == 'SF')
ggplot(df_wq, aes(Date, DissNitrateNitrite, color = DS)) +
  geom_point()
```
```{r}
unique(df_wq$DS)
```

