```{r}
# Title: Process SF WQ Data
# Purpose: process and clean SF wq data for drought synthesis
# Author: Sarah Perry
# Contact: sarah.perry@water.ca.gov
```

```{r}
library(tidyverse)
library(deltamapr)
library(lubridate)
library(sf)
library(sp)
source('Water_Quality/wq_funcs.R')
```

```{r, message = FALSE}
fp_abs_wq <- 'WQ_Team/raw_data/USGS_CAWSC/USGS_CAWSC_1975_2021.csv'
fp_abs_meta <- 'WQ_Team/raw_data/metadata_wq_files/'

df_wq <- read_csv(drought_abs_path(fp_abs_wq))

df_wq <- rename(df_wq, Date = activity_start_date, site_no = monitoring_location_identifier, Analyte = characteristic_name, Value = result_measure_value)
df_wq$site_no <- lapply(df_wq$site_no, function(x) str_split(x, '-', 2)[[1]][[2]])
df_wq$site_no <- unlist(df_wq$site_no)
```


```{r, message = FALSE}
df_wy <- read_csv(drought_abs_path(paste0(fp_abs_meta,'Year_assignments.csv')))
df_regions <- read_csv(drought_abs_path(paste0(fp_abs_meta,'drought_regions.csv')))
df_coords <- read_csv(drought_abs_path(paste0(fp_abs_meta,'USGS_CAWSC_stations.csv')))

df_coords <- rename(df_coords, site_no = NWIS_ID)
df_coords$site_no <- as.character(df_coords$site_no)

df_wq <- left_join(df_wq, df_coords, by = 'site_no')
df_wq <- subset(df_wq, !(Site_Abbrev %in% c('ROD','PCT')))

df_wq <- subset(df_wq, select = c(Site_Abbrev, Date, Analyte, Value, Lat, Long))
row.names(df_wq) <- NULL
df_wq$ID <- seq.int(nrow(df_wq))

df_wq <- df_wq %>%
  pivot_wider(id_cols = c(ID, Site_Abbrev, Date, Lat, Long), values_from = Value, names_from = Analyte)
```
PCT and FER also share a site ID/datetime stamp

```{r}
#import delta sf
sf_delta <- R_EDSM_Subregions_Mahardja_FLOAT

# combine & clean up wq datasets
df_wq <- df_wq %>% rename(Station = Site_Abbrev,
                          DissNitrateNitrite = `Inorganic nitrogen (nitrate and nitrite)`,,
                          DissAmmonia = `Ammonia and ammonium`,
                          DissOrthophos = Orthophosphate,
                          Latitude = Lat,
                          Longitude = Long)

df_wq <- subset(df_wq, select = c(Station, Date, DissNitrateNitrite, DissAmmonia, DissOrthophos, Latitude, Longitude))
df_wq$Date <- as.Date(df_wq$Date, format = '%Y-%m-%d')

df_wq <- add_season_col(df_wq)

df_wq <- subset(df_wq, !c(is.na(DissAmmonia) & is.na(DissOrthophos) & is.na(DissNitrateNitrite)))

df_wq$Year <- year(df_wq$Date)
df_wq$Month <- month(df_wq$Date)
df_wq$Year <- with(df_wq, ifelse(month(Date) == 12, Year+1, Year))

df_wq <- add_wy_col(df_wq, df_wy)

df_wq <- df_wq %>%
  group_by(Station, Date, Year, Month, Season, Drought, YearType, Longitude, Latitude) %>%
  summarize(across(DissNitrateNitrite:DissOrthophos, ~mean(., na.rm = TRUE)), .groups = 'drop')
  
df_wq <- df_wq[order(df_wq$Date),]
```

```{r}
# convert wq to spdf
coords <- df_wq[,c('Longitude', 'Latitude')]
data   <- df_wq
crs    <- CRS('+init=epsg:4326 +proj=longlat')
spdf_wq <- SpatialPointsDataFrame(coords = coords,
                               data = data, 
                               proj4string = crs)

# convert delta to spdf
spdf_delta <- as(sf_delta, 'Spatial')
spdf_delta <- spTransform(spdf_delta, CRS('+init=epsg:4326 +proj=longlat'))

# add subregion col to wq df
col_sr <- sp::over(spdf_wq, spdf_delta[,'SubRegion'])
spdf_wq$SubRegion <- col_sr$SubRegion

# convert to shapefile
sf_wq <- st_as_sf(spdf_wq)
sf_wq <- st_transform(sf_wq, st_crs = sf_delta)

# add longterm col
sf_wq_lt <- merge(sf_wq, df_regions[,c('Long_term','Season','SubRegion','Region')], by = c('Season','SubRegion'))

# check data
ggplot() + 
  geom_sf(data = sf_delta) + 
  #geom_sf_text(data = sf_delta, aes(label = SubRegion)) +
  geom_sf(data = sf_wq_lt, aes(color = Long_term))
```

```{r}
# check extra regions in original wq df (ie. not in sf_wq_lt)
unique(sf_wq$SubRegion)[!(unique(sf_wq$SubRegion) %in% unique(df_regions$SubRegion))]
```

```{r}
# add lat/lon cols and export
sf_wq_lt$Longitude <- apply(st_coordinates(sf_wq_lt), 1, function(x) x[1])
sf_wq_lt$Latitude <- apply(st_coordinates(sf_wq_lt), 1, function(x) x[2])
df_wq_lt <- as_tibble(sf_wq_lt)

df_wq_lt <- subset(df_wq_lt, select = -c(geometry))

write_csv(df_wq_lt, drought_abs_path('WQ_Team/processed_data/USGS_CAWSC_1971-2021.csv'))
```

