```{r}
# Title: Exploratory analysis of WQ data
# Purpose: determine best regressions to use for the drought synthesis project
# Author: Sarah Perry
# Contact: sarah.perry@water.ca.gov
```

```{r}
library(car)
library(english)
library(tseries)
library(tidyverse)
library(lubridate)
library(emmeans)
source('Water_Quality/wq_funcs.R')
```

# Read in Data
(removing WSC because it's short-term only)
```{r message = FALSE}
df_wq <- read_csv(drought_abs_path('WQ_Team/processed_data/combined_wq_data.csv'))

df_wq <- subset(df_wq, DS %in% c('SF', 'EMP'))

# df_wq$Drought <- ifelse(df_wq$Drought %in% c('N','W'), 'ND', df_wq$Drought)
df_wq$Year <- as.numeric(unlist(lapply(as.character(df_wq$Date), function(x) strsplit(x, '-')[[1]][1])))
df_wq$Year <- with(df_wq, ifelse(month(Date) == 12, Year+1, Year))
```

```{r}
# Seasonal
df_wq_seasonal <- df_wq %>%
  group_by(Year, YearType, Drought, Season, Long_term) %>%
  summarise_at(c('DissNitrateNitrite', 'DissOrthophos', 'DissAmmonia'), mean, na.rm = TRUE)

df_wq_seasonal$DissNitrateNitrite <- log10(df_wq_seasonal$DissNitrateNitrite)
df_wq_seasonal$DissOrthophos <- log10(df_wq_seasonal$DissOrthophos)
df_wq_seasonal$DissAmmonia <- log10(df_wq_seasonal$DissAmmonia)

df_wq_seasonal$Year_Season <- paste0(df_wq_seasonal$Year,'-',df_wq_seasonal$Season)
```

# Seasonal Averages for Entire Delta (DissNitrateNitrite)
```{r}
print('TEST THINGS')
lm_seasonal <- lm(DissNitrateNitrite ~ Drought + Season, data = df_wq_seasonal)

pacf(residuals(lm_seasonal), na.action = na.pass)

print(stats::Box.test(residuals(lm_seasonal), type = 'Ljung'))
print('')
print('END TEST THINGS')
print('')

print('passed tests')

print('')
print('*-*-*-*-*-*-*')
print('')

plot(lm_seasonal)

aov_seasonal <- Anova(lm_seasonal, type = 'II', test.statistic = 'F')
print(aov_seasonal)

print('')
print('*-*-*-*-*-*-*')
print('')

emm_seas_seas <- emmeans(lm_seasonal, specs = pairwise ~ Season:Season, adjust = 'sidak')
print(test(emm_seas_seas)$contrasts)

print('')
print('*-*-*-*-*-*-*')
print('')

emm_seas_WY <- emmeans(lm_seasonal, specs = pairwise ~ Drought:Drought, adjust = 'sidak')
print(test(emm_seas_WY)$contrasts)
```

# Seasonal Averages for Entire Delta (DissAmmonia)
```{r}
print('TEST THINGS')
lm_seasonal <- lm(DissAmmonia ~ Drought + Season, data = df_wq_seasonal)

pacf(residuals(lm_seasonal), na.action = na.pass)

print(stats::Box.test(residuals(lm_seasonal), type = 'Ljung'))
print('')
print('END TEST THINGS')
print('')

# failed tests, add lags based on pacf
df_wq_seasonal$DissAmmonia_onelag <- lag(df_wq_seasonal$DissAmmonia, n = 1L)
df_wq_seasonal$DissAmmonia_twolag <- lag(df_wq_seasonal$DissAmmonia, n = 2L)

lm_seasonal <- lm(DissAmmonia ~ Drought + Season + DissAmmonia_onelag, data = df_wq_seasonal)

pacf(residuals(lm_seasonal), na.action = na.pass)

print(stats::Box.test(residuals(lm_seasonal), type = 'Ljung'))
print('')
print('*-*-*-*-*-*-*')
print('')

plot(lm_seasonal)

aov_seasonal <- Anova(lm_seasonal, type = 'II', test.statistic = 'F')
print(aov_seasonal)

print('')
print('*-*-*-*-*-*-*')
print('')

emm_seas_seas <- emmeans(lm_seasonal, specs = pairwise ~ Season:Season, adjust = 'sidak')
print(test(emm_seas_seas)$contrasts)

print('')
print('*-*-*-*-*-*-*')
print('')

emm_seas_WY <- emmeans(lm_seasonal, specs = pairwise ~ Drought:Drought, adjust = 'sidak')
print(test(emm_seas_WY)$contrasts)
```

# Seasonal Averages for Entire Delta (DissOrthophos)
```{r}
print('TEST THINGS')
lm_seasonal <- lm(DissOrthophos ~ Drought + Season, data = df_wq_seasonal)

pacf(residuals(lm_seasonal), na.action = na.pass)

print(stats::Box.test(residuals(lm_seasonal), type = 'Ljung'))

print('')
print('END TEST THINGS')
print('')

# failed tests, add lags based on pacf
df_wq_seasonal$DissOrthophos_onelag <- lag(df_wq_seasonal$DissOrthophos, n = 1L)
df_wq_seasonal$DissOrthophos_twolag <- lag(df_wq_seasonal$DissOrthophos, n = 2L)

lm_seasonal <- lm(DissOrthophos ~ Drought + Season + DissOrthophos_onelag + DissOrthophos_twolag, data = df_wq_seasonal)

pacf(residuals(lm_seasonal), na.action = na.pass)

print(stats::Box.test(residuals(lm_seasonal), type = 'Ljung'))
print('')
print('*-*-*-*-*-*-*')
print('')

plot(lm_seasonal)

aov_seasonal <- Anova(lm_seasonal, type = 'II', test.statistic = 'F')
print(aov_seasonal)

print('')
print('*-*-*-*-*-*-*')
print('')

emm_seas_seas <- emmeans(lm_seasonal, specs = pairwise ~ Season:Season, adjust = 'sidak')
print(test(emm_seas_seas)$contrasts)

print('')
print('*-*-*-*-*-*-*')
print('')

emm_seas_WY <- emmeans(lm_seasonal, specs = pairwise ~ Drought:Drought, adjust = 'sidak')
print(test(emm_seas_WY)$contrasts)
```

```{r}
# Regional
df_wq_regional <- df_wq %>%
  group_by(Year, Region, YearType, Drought, Long_term) %>%
  summarise_at(c('DissNitrateNitrite', 'DissOrthophos', 'DissAmmonia'), mean, na.rm = TRUE)

df_wq_regional$DissNitrateNitrite <- log10(df_wq_regional$DissNitrateNitrite)
df_wq_regional$DissOrthophos <- log10(df_wq_regional$DissOrthophos)
df_wq_regional$DissAmmonia <- log10(df_wq_regional$DissAmmonia)
```

# Regional Averages per Year (DissNitrateNitrite)
```{r}
print('TEST THINGS')
lm_regional <- lm(DissNitrateNitrite ~ Drought + Region, data = df_wq_regional)

pacf(residuals(lm_regional), na.action = na.pass)

print(stats::Box.test(residuals(lm_regional), type = 'Ljung'))

print('')
print('END TEST THINGS')
print('')
print('PASSED TESTS')
print('')
print('*-*-*-*-*-*-*')
print('')

plot(lm_regional)

aov_regional <- Anova(lm_regional, type = 'II', test.statistic = 'F')
print(aov_regional)

print('')
print('*-*-*-*-*-*-*')
print('')

emm_reg_reg <- emmeans(lm_regional, specs = pairwise ~ Region:Region, adjust = 'sidak')
print(test(emm_reg_reg)$contrasts)

print('')
print('*-*-*-*-*-*-*')
print('')

emm_reg_WY <- emmeans(lm_regional, specs = pairwise ~ Drought:Drought, adjust = 'sidak')
print(test(emm_reg_WY)$contrasts)
```

# Regional Averages per Year (DissAmmonia)
```{r}
print('TEST THINGS')
lm_regional <- lm(DissAmmonia ~ Drought + Region, data = df_wq_regional)

pacf(residuals(lm_regional), na.action = na.pass)

print(stats::Box.test(residuals(lm_regional), type = 'Ljung'))

print('')
print('END TEST THINGS')
print('')
print('PASSED TESTS')
print('')
print('*-*-*-*-*-*-*')
print('')

plot(lm_regional)

aov_regional <- Anova(lm_regional, type = 'II', test.statistic = 'F')
print(aov_regional)

print('')
print('*-*-*-*-*-*-*')
print('')

emm_reg_reg <- emmeans(lm_regional, specs = pairwise ~ Region:Region, adjust = 'sidak')
print(test(emm_reg_reg)$contrasts)

print('')
print('*-*-*-*-*-*-*')
print('')

emm_reg_WY <- emmeans(lm_regional, specs = pairwise ~ Drought:Drought, adjust = 'sidak')
print(test(emm_reg_WY)$contrasts)
```

# Regional Averages per Year (DissOrthophos)
```{r}
print('TEST THINGS')
lm_regional <- lm(DissOrthophos ~ Drought + Region, data = df_wq_regional)

pacf(residuals(lm_regional), na.action = na.pass)

print(stats::Box.test(residuals(lm_regional), type = 'Ljung'))

print('')
print('END TEST THINGS')
print('')

# failed tests, add lags based on pacf
df_wq_regional$DissOrthophos_onelag <- lag(df_wq_regional$DissOrthophos, n = 1L)
df_wq_regional$DissOrthophos_twolag <- lag(df_wq_regional$DissOrthophos, n = 2L)

lm_regional <- lm(DissOrthophos ~ Drought + Region  + DissOrthophos_onelag + DissOrthophos_twolag, data = df_wq_regional)

pacf(residuals(lm_regional), na.action = na.pass)

print(stats::Box.test(residuals(lm_regional), type = 'Ljung'))
print('')
print('*-*-*-*-*-*-*')
print('')

plot(lm_regional)

aov_regional <- Anova(lm_regional, type = 'II', test.statistic = 'F')
print(aov_regional)

print('')
print('*-*-*-*-*-*-*')
print('')

emm_reg_reg <- emmeans(lm_regional, specs = pairwise ~ Region:Region, adjust = 'sidak')
print(test(emm_reg_reg)$contrasts)

print('')
print('*-*-*-*-*-*-*')
print('')

emm_reg_WY <- emmeans(lm_regional, specs = pairwise ~ Drought:Drought, adjust = 'sidak')
print(test(emm_reg_WY)$contrasts)
```
