```{r}
# Title: Drought Graphs
# Purpose: create graphs for drought synthesis
# Author: Sarah Perry
# Contact: sarah.perry@water.ca.gov
```

```{r}
library(DroughtData)
library(tidyverse)
source('Water_Quality/wq_graph_funcs.R')
```

```{r}
# read in data
df_wq <- raw_nutr_1975_2021
df_wq <- drt_add_yr_assign(df_wq)
df_wq <- df_wq %>%
    mutate(across(c(Drought, YearType), list(`20_21`=~case_when(YearAdj==2021 ~ "2021", 
                                                              YearAdj==2020 ~ "2020", 
                                                              TRUE ~ as.character(.x)))),
         across(c(YearType, YearType_20_21), ~factor(.x, levels=c("2020", "2021", "Critical", "Dry", "Below Normal", "Above Normal", "Wet"))),
         Region=factor(Region, levels=c("Suisun Marsh", "Suisun Bay", "Confluence", "SouthCentral", "North")),
         Season=factor(Season, levels=c("Winter", "Spring", "Summer", "Fall")))

# df_wq$YearType[df_wq$YearType == 'Below Normal'] <- 'Below Norm'
# df_wq$YearType[df_wq$YearType == 'Above Normal'] <- 'Above Norm'
```

```{r}
# remove outlier vals
df_wq <- df_wq %>% filter(
  !c(DissAmmonia_Sign == '<' & DissAmmonia >= .2),
  !c(DissOrthophos_Sign == '<' & DissOrthophos > .15),
  !c(DissNitrateNitrite_Sign == '<' & DissNitrateNitrite >= 3)
  )
```

```{r}
# boxplots

# year type
for (analyte in c('DissAmmonia','DissOrthophos','DissNitrateNitrite')){
  full_name <- assign_full_name(analyte)
  ylim_cut <- assign_cutoffs(analyte)

  df_bp <- gen_bp_data(df_wq, analyte, group = 'YearType_20_21', metadat = c('YearType'))
  
  plt_bp <- create_bp(df_bp, x = 'YearType_20_21', fill = 'YearType', show_outliers = TRUE)
  plt_bp <- plt_bp +
    drt_color_pal_yrtype() +
    theme_bw() +
    theme(legend.position = 'top', axis.text.x = element_text(angle = 13, vjust = 0.5)) +
    ylab(paste(full_name,'(mg/L)')) +
    xlab('Year/Drought') +
    ylim(0,ylim_cut)
  
  # print(plt_bp)
  
 ggsave(paste0(getwd(),'/Water_Quality/plots/bp_',analyte,'_yt.jpg'),plt_bp, width = 5.5, height = 4)
}

# drought index
for (analyte in c('DissAmmonia','DissOrthophos','DissNitrateNitrite')){
  full_name <- assign_full_name(analyte)
  ylim_cut <- assign_cutoffs(analyte)
  
  df_bp <- gen_bp_data(df_wq, analyte, group = c('Drought_20_21'), metadat = c('Drought'))
  
  plt_bp <- create_bp(df_bp, x = 'Drought_20_21', fill = 'Drought', show_outliers = TRUE)
  plt_bp <- plt_bp +
    drt_color_pal_drought() +
    theme_bw() +
    theme(legend.position = 'top') +
    ylab(paste(full_name,'(mg/L)')) +
    xlab('Year/Drought') +
    ylim(0,ylim_cut)
  
  # print(plt_bp)
  
  ggsave(paste0(getwd(),'/Water_Quality/plots/bp_',analyte,'_di.jpg'),plt_bp, width = 5.5, height = 4)
}
```

